### ISSUE TITLE
Same resilience4j version is not working for me

### ISSUE THREAD

**Issue by mayurgite** [srinivasboini/resilience4j-bulkhead-threadpool#1]
Hi , 
I am working on similar implementation, I am referring same pom version along with same yml but still I am getting following issue:
`
APPLICATION FAILED TO START

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.github.resilience4j.spring6.bulkhead.configure.threadpool.ThreadPoolBulkheadConfiguration.createBulkheadRegistry(ThreadPoolBulkheadConfiguration.java:105)

The following method did not exist:

    'io.github.resilience4j.bulkhead.ThreadPoolBulkheadRegistry io.github.resilience4j.bulkhead.ThreadPoolBulkheadRegistry.of(java.util.Map, io.github.resilience4j.core.registry.RegistryEventConsumer, java.util.Map)'

The calling method's class, io.github.resilience4j.spring6.bulkhead.configure.threadpool.ThreadPoolBulkheadConfiguration, was loaded from the following location:

    jar:file:/home/WORLDPAY.LOCAL/gitem978/.m2/repository/io/github/resilience4j/resilience4j-spring6/2.2.0/resilience4j-spring6-2.2.0.jar!/io/github/resilience4j/spring6/bulkhead/configure/threadpool/ThreadPoolBulkheadConfiguration.class

The called method's class, io.github.resilience4j.bulkhead.ThreadPoolBulkheadRegistry, is available from the following locations:

    jar:file:/home/WORLDPAY.LOCAL/gitem978/.m2/repository/io/github/resilience4j/resilience4j-bulkhead/1.7.0/resilience4j-bulkhead-1.7.0.jar!/io/github/resilience4j/bulkhead/ThreadPoolBulkheadRegistry.class

The called method's class hierarchy was loaded from the following locations:

    io.github.resilience4j.bulkhead.ThreadPoolBulkheadRegistry: file:/home/WORLDPAY.LOCAL/gitem978/.m2/repository/io/github/resilience4j/resilience4j-bulkhead/1.7.0/resilience4j-bulkhead-1.7.0.jar

Action:

Correct the classpath of your application so that it contains compatible versions of the classes io.github.resilience4j.spring6.bulkhead.configure.threadpool.ThreadPoolBulkheadConfiguration and io.github.resilience4j.bulkhead.ThreadPoolBulkheadRegistry`

I am confused now, am I missing something here?

**Comment by srinivasboini** [comment]
Hi @mayurgite ,

It looks like you are using resilience4j-spring6 and its pulling resilience4j-bulkhead 1.7.0 version. This is completely different from what I am using. 

below is my only dependency which pulls are the required deps.

```
		<dependency>
			<groupId>io.github.resilience4j</groupId>
			<artifactId>resilience4j-spring-boot3</artifactId>
			<version>2.2.0</version>
		</dependency>
```

You can share your repo where you are facing the issue. I will try to help..

Thanks,
Srinivas

**Comment by srinivasboini** [comment]
closing as it is not a defect
